name: "Shared: Labeler"

on:
  - "pull_request_target"

jobs:
  triage:
    name: "Triage"
    runs-on: self-hosted

    permissions:
      contents: "read"
      pull-requests: "write"

    steps:
      - uses: "actions/labeler@v5"
        with:
          configuration-path: ".github/labeler.yaml"
          sync-labels: true
